# Generated by Django 4.2.1 on 2024-06-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='brand_name',
            field=models.CharField(default='Unknown Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='dessert',
            name='image',
            field=models.ImageField(default='NULL', upload_to='dessert_images/'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dessert',
            name='product_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='dessert',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='brand_name',
            field=models.CharField(default='Unknown Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='image',
            field=models.ImageField(default='NULL', upload_to='main_course_images/'),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='product_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='starter',
            name='brand_name',
            field=models.CharField(default='Unknown Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='starter',
            name='image',
            field=models.ImageField(default='NULL', upload_to='starter_images/'),
        ),
        migrations.AddField(
            model_name='starter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='starter',
            name='product_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='starter',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
